from enum import Enum

DOOR_STATUS = Enum("DOOR_STATUS", "CLOSED OPENED")
MOTOR_STATUS = Enum("MOTOR_STATUS", "MOVING STOPPED")
DIRECTION = Enum("DIRECTION", "UP DOWN")
VENDOR_ID = Enum("VENDOR_ID", "LG HYUNDAI SAMSUNG")

